### PR TITLE
bump version

### PR DESCRIPTION
**Pull request by timelf123**

### CODE REVIEW

**Comment by R0GGER** [comment]
Thanks!

**Comment by timelf123** [comment]
Oops - make sure you test this one. I thought the issue was my reverse proxy, but I am getting errors in the container now:

`fatal: unable to start ./run: file does not exist`

Edit - user error

**Comment by R0GGER** [comment]
Try to pull the docker image again... 
docker pull r0gger/mistserver

**Comment by timelf123** [comment]
I was building locally - fixed it, thanks

**Pull request merged**
